import React from 'react';
import { Dialog, DialogTitle, DialogContent, DialogActions, Button, Typography, Link, Box } from '@mui/material';

type Props = {
  open: boolean;
  onAccept: () => void;
  onCancel?: () => void;
};

export default function TermsModal({ open, onAccept, onCancel }: Props) {
  return (
    <Dialog open={open}  maxWidth="md" fullWidth>
      <DialogTitle><b>Underwritre Terms and Conditions</b></DialogTitle>
      <DialogContent dividers>
        <Typography sx={{ mb: 2 }}>
          By continuing, you acknowledge that you have read and agree to the UnderwritRE Terms and Conditions, and
          understand that the Platform does not provide financial, investment, or legal advice.{' '}
          <Link href={'https://storage.googleapis.com/uw_resources/Underwritre_terms_and_conditions.pdf'} target="_blank" rel="noopener">
            View full Terms (PDF)
          </Link>
        </Typography>
        <Box sx={{ maxHeight: 360, overflow: 'auto', p: 2, border: '1px solid #e0e0e0', borderRadius: 1 }}>
          <Typography variant="h6" sx={{ mb: 1 }}>UnderwritRE Terms of Use and Legal Disclaimer</Typography>
          <Typography sx={{ mb: 1 }}><strong>1. Acceptance of Terms</strong><br/>
          By accessing or using UnderwritRE (“the Platform,” “we,” “our,” or “us”), you agree to these Terms of Use (“Terms”). If you do not agree, do not access or use the Platform.
          We may update these Terms from time to time. Continued use of the Platform after changes are posted constitutes acceptance of those changes.</Typography>
          <Typography sx={{ mb: 1 }}><strong>2. Nature of Services</strong><br/>
          UnderwritRE provides software tools designed to assist users in organizing, modeling, and analyzing real estate and investment assumptions.
          We are not a licensed financial institution, investment adviser, broker-dealer, or underwriter.
          The Platform is intended solely for informational and educational purposes to help users structure and visualize their own analyses. Nothing on the Platform constitutes:
          Investment, legal, accounting, or tax advice; An offer to buy or sell securities, real estate, or any other financial instrument; A recommendation or endorsement of any investment strategy, property, or transaction.
          You are solely responsible for your own decisions, analyses, and outcomes. Always seek advice from qualified professionals before making financial or investment decisions.</Typography>
          <Typography sx={{ mb: 1 }}><strong>3. User Responsibilities</strong><br/>
          You agree that: You will provide accurate and lawful information when using the Platform. You are responsible for maintaining the confidentiality of your account credentials. You will not use the Platform for unlawful, fraudulent, or misleading purposes. You understand that outputs and results generated by the Platform depend entirely on your own input data and assumptions. We do not guarantee the accuracy, completeness, or reliability of any model outputs or data.</Typography>
          <Typography sx={{ mb: 1 }}><strong>4. No Warranty</strong><br/>
          The Platform and all associated data, content, and services are provided “as is” and “as available” without warranties of any kind, express or implied, including but not limited to: Accuracy or completeness of results or calculations; Fitness for a particular purpose; Non-infringement; Availability or error-free operation. UnderwritRE does not warrant that the Platform will be uninterrupted or free from defects, errors, or security vulnerabilities.</Typography>
          <Typography sx={{ mb: 1 }}><strong>5. Limitation of Liability</strong><br/>
          To the fullest extent permitted by law: UnderwritRE and its founders, officers, employees, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the Platform, including but not limited to loss of data, profits, opportunities, or goodwill. Our aggregate liability to you shall not exceed the greater of (a) the amount paid by you to UnderwritRE in the past 12 months, or (b) $100 USD.</Typography>
          <Typography sx={{ mb: 1 }}><strong>6. User Data and Privacy</strong><br/>
          We collect and process certain information you provide in accordance with our Privacy Policy (to be linked). By using the Platform, you consent to the collection and use of this information for the purpose of providing and improving our services. You retain ownership of your input data and models. By using the Platform, you grant UnderwritRE a limited license to process that data for the purpose of operating the service.</Typography>
          <Typography sx={{ mb: 1 }}><strong>7. Intellectual Property</strong><br/>
          All Platform content, including but not limited to software, code, designs, logos, and documentation, are the property of UnderwritRE or its licensors and are protected by applicable intellectual property laws. You may not copy, distribute, reverse-engineer, or modify any part of the Platform without our written consent.</Typography>
          <Typography sx={{ mb: 1 }}><strong>8. Third-Party Links and Data</strong><br/>
          The Platform may include links to or data from third-party websites, APIs, or content providers. UnderwritRE does not endorse, guarantee, or assume responsibility for any third-party information, products, or services.</Typography>
          <Typography sx={{ mb: 1 }}><strong>9. Termination</strong><br/>
          We may suspend or terminate your access to the Platform at any time for any reason, including but not limited to violation of these Terms. Upon termination, your right to use the Platform will immediately cease.</Typography>
          <Typography sx={{ mb: 1 }}><strong>10. Governing Law</strong><br/>
          These Terms are governed by and construed in accordance with the laws of the State of New Jersey, without regard to its conflict-of-law principles. Any disputes arising under or in connection with these Terms shall be resolved in the state or federal courts located in Essex County, New Jersey.</Typography>
          <Typography sx={{ mb: 1 }}><strong>11. Contact</strong><br/>
          For questions or concerns regarding these Terms, contact: support@underwritre.com</Typography>
        </Box>
      </DialogContent>
      <DialogActions>
        {/* <Button onClick={onCancel}>Cancel</Button> */}
        <Button variant="contained" onClick={onAccept}>I Agree</Button>
      </DialogActions>
    </Dialog>
  );
}


